// ═══════════════════════════════════════════════════════
//  PRODUCTOS.JS  —  Aquí editas todo tu catálogo
//
//  CÓMO AGREGAR UN PRODUCTO:
//  Copia un bloque { ... } y pégalo antes del último ]
//  separado por coma.
//
//  CÓMO AGREGAR UNA VARIANTE:
//  Dentro de "variantes", agrega una línea:
//  { nombre: "Nombre de la veladora" },
//
//  Si una variante tiene precio diferente al base, agrégalo:
//  { nombre: "Veladora Jumbo Roja", precio: "$25 mxn" },
// ═══════════════════════════════════════════════════════

const productos = [

  // ─────────────────────────────────────────────────────
  //  PRODUCTO 1
  // ─────────────────────────────────────────────────────
  {
    titulo:      "Veladoras de parafina",
    img:         "veladoraparafina.png",
    descripcion: "Velas artesanales en parafina. Colores y aromas especialmente formulados para rituales y meditación.",
    precioBase:  "Desde $590 mxn / caja (20 pzas)",
    variantes: [
      { nombre: "Atrayente" },
{ nombre: "Amarre total" },
{ nombre: "Abre camino" },
{ nombre: "Amarre" },
{ nombre: "Amarre haitiano" },
{ nombre: "Azúcar" },
{ nombre: "Amarrador" },
{ nombre: "Atrapa clientes" },
{ nombre: "Ajo macho" },
{ nombre: "Aborrecido serás" },
{ nombre: "Arrasa brujería" },
{ nombre: "Amarre matrimonial" },
{ nombre: "Anima sola" },
{ nombre: "Arrasa todo dragón" },
{ nombre: "Arrasa todo coyote" },
{ nombre: "Arcángel Gabriel" },
{ nombre: "Arcángel Rafael" },
{ nombre: "Arcángel Zadkiel" },
{ nombre: "Arcángel Uriel" },
{ nombre: "Arcángel Chamuel" },
{ nombre: "Arcángel Jofiel" },
{ nombre: "Arcángel Miguel" },
{ nombre: "Buena suerte y protección" },
{ nombre: "Brasero" },
{ nombre: "Contra daños" },
{ nombre: "Canela" },
{ nombre: "Chuparosa" },
{ nombre: "Contra embrujo" },
{ nombre: "Cordero manso" },
{ nombre: "Correlona" },
{ nombre: "Corta maldad" },
{ nombre: "Corte y juzgado" },
{ nombre: "Cruz de Caravaca" },
{ nombre: "Cuerno de la abundancia" },
{ nombre: "Cocktel 33" },
{ nombre: "Coyote" },
{ nombre: "Corta espanto" },
{ nombre: "Con nadie mas podrás" },
{ nombre: "Contra envidia" },
{ nombre: "Coco" },
{ nombre: "Chile" },
{ nombre: "Coco/ canela" },
{ nombre: "Corta enfermedad" },
{ nombre: "Desespero" },
{ nombre: "Destierro" },
{ nombre: "Destrancadera" },
{ nombre: "Divina providencia" },
{ nombre: "Doble suerte rápida" },
{ nombre: "Doblegado a mis pies" },
{ nombre: "Domina todo" },
{ nombre: "Don Juan del dinero" },
{ nombre: "Desamarre" },
{ nombre: "Detente enemigo" },
{ nombre: "Divina providencia" },
{ nombre: "Dominio" },
{ nombre: "Odio" },
{ nombre: "Doble suerte rápida" },
{ nombre: "Dólar" },
{ nombre: "Domino mujer" },
{ nombre: "Domino hombre" },
{ nombre: "Estudiante" },
{ nombre: "El bien y el mal" },
{ nombre: "Elegua" },
{ nombre: "Espíritu dominador" },
{ nombre: "Espíritu santo" },
{ nombre: "Espíritu intranquilo" },
{ nombre: "Esposo cumplidor" },
{ nombre: "Éxito" },
{ nombre: "Embrujo de amor" },
{ nombre: "Espanta muerto" },
{ nombre: "Fidelidad" },
{ nombre: "Furia de paciones" },
{ nombre: "Gallina negra" },
{ nombre: "Garrapata" },
{ nombre: "Gato negro" },
{ nombre: "Gana juicio" },
{ nombre: "Harás mi voluntad" },
{ nombre: "Hechizo de amor" },
{ nombre: "Hechizo gitano" },
{ nombre: "Herradura" },
{ nombre: "Jala jala" },
{ nombre: "Justo juez" },
{ nombre: "Jesús malverde" },
{ nombre: "Jorobado" },
{ nombre: "Juan conquistador" },
{ nombre: "Juzgador de leyes" },
{ nombre: "Job (Trabajo)" },
{ nombre: "Lavanda" },
{ nombre: "Levanta negocios" },
{ nombre: "Limpia aura" },
{ nombre: "Limpia cuerpo" },
{ nombre: "Limpias y despojos" },
{ nombre: "Limpias" },
{ nombre: "Llama cliente" },
{ nombre: "Llama dinero" },
{ nombre: "Luvia de dinero" },
{ nombre: "Lluvia de estrellas" },
{ nombre: "Lluvia de suerte" },
{ nombre: "Mano poderosa" },
{ nombre: "Miel de amor" },
{ nombre: "Nardos" },
{ nombre: "Nueve yerbas del indio" },
{ nombre: "Niño de la salud" },
{ nombre: "Obatala" },
{ nombre: "Ogum" },
{ nombre: "Patchuly" },
{ nombre: "Págame pronto" },
{ nombre: "Para todo" },
{ nombre: "Paz en el hogar" },
{ nombre: "Perro cazador" },
{ nombre: "Piensa en mi" },
{ nombre: "Pierde rumbo" },
{ nombre: "Prosperidad" },
{ nombre: "Protección" },
{ nombre: "Quédate en casa" },
{ nombre: "Quiéreme siempre" },
{ nombre: "Quiero trabajo pronto" },
{ nombre: "Quita maldición" },
{ nombre: "Quita vicio" },
{ nombre: "Retira trabajo negro" },
{ nombre: "Regresa a casa" },
{ nombre: "Regresa a mi" },
{ nombre: "Regresa pronto" },
{ nombre: "Retiro" },
{ nombre: "Retiro" },
{ nombre: "Retiro" },
{ nombre: "Reversible" },
{ nombre: "Rey salomón" },
{ nombre: "Rompe camino" },
{ nombre: "Rompe maleficios" },
{ nombre: "Rompe hechizos" },
{ nombre: "Rosas" },
{ nombre: "Rosas con miel" },
{ nombre: "Saca sal" },
{ nombre: "Separa amantes" },
{ nombre: "Shangoo" },
{ nombre: "Siete arcángeles" },
{ nombre: "Siete potencias" },
{ nombre: "Siete machos" },
{ nombre: "Siete nudos" },
{ nombre: "Siete veces reversible" },
{ nombre: "Sígueme y obedéceme" },
{ nombre: "Solo mío serás" },
{ nombre: "Santa muerte blanca" },
{ nombre: "Santa muerte roja" },
{ nombre: "Santa muerte negra" },
{ nombre: "Santa muerte (del titulo que usted necesite)" },
{ nombre: "Taba pocas" },
{ nombre: "Triple suerte" },
{ nombre: "Tumba trabajo" },
{ nombre: "Tumba trabajo negro" },
{ nombre: "Te odiara tu amante" },
{ nombre: "Tapa camino" },
{ nombre: "Unión" },
{ nombre: "Unión familiar" },
{ nombre: "Unión matrimonial" },
{ nombre: "Ven a mi" },
{ nombre: "Velo de novia" },
{ nombre: "Ven dinero" },
{ nombre: "Vence batallas" },
{ nombre: "Vuelve conmigo" },
{ nombre: "Vete lejos" },
{ nombre: "Voladora" },
{ nombre: "Vencedor" },
{ nombre: "Ventas rápidas" },
{ nombre: "Yemaya" },
{ nombre: "Yo domino a mi hija" },
{ nombre: "Yo domino hijo" },
{ nombre: "Yo domino a mi hombre" },
{ nombre: "Yo domino a mi mujer" },
{ nombre: "Yo domino a mi patrón" },
{ nombre: "Yo puedo mas que tu" },
{ nombre: "Zodiaco" },
{ nombre: "Orula" },
{ nombre: "Oshun" },
      // EDITAR: agrega más variantes aquí con el mismo formato
    ]
  },

  // ─────────────────────────────────────────────────────
  //  PRODUCTO 2
  // ─────────────────────────────────────────────────────
  {
    titulo:      "Veladoras de Gel",
    img:         "IMG_4718.jpeg",
    descripcion: "Veladoras de figuras de parafina y gel diseñadas para diferentes propositos.",
    precioBase:  "Desde $1,100 mxn / caja (20 pzas)",
    variantes: [
      { nombre: "San Judas Tadeo" },
      { nombre: "Virgen de Guadalupe" },
      { nombre: "Santa Muerte" },
      { nombre: "San Simon" },
      { nombre: "Ven Dinero"},
      { nombre: "Doble Suerte"},
      { nombre: "Triple Suerte"},
      { nombre: "Levanta Negocios"},
      { nombre: "Yo puedo mas que tu"},
      { nombre: "Con nadie mas podras"},
      { nombre: "Amarre Matrimonial"},
      { nombre: "Amarre Guajiro"},
      { nombre: "Amarre Total"},
      // EDITAR: agrega más variantes aquí
    ]
  },

  // ─────────────────────────────────────────────────────
  //  PRODUCTO 3
  // ─────────────────────────────────────────────────────
  {
    titulo:      "Lociones Wiskeras",
    img:         "3FBF1197-ACE1-4801-87D0-2D7773CBCF80.png",
    descripcion: "Lociones naturales hechas a base de extractos de plantas y minerales ideales para su petición.",
    precioBase:  "Desde $19 mxn / unidad",
    variantes: [
      { nombre: "Amarre total" },
{ nombre: "Abre camino" },
{ nombre: "Amarre" },
{ nombre: "Amarre haitiano" },
{ nombre: "Azúcar" },
{ nombre: "Amarrador" },
{ nombre: "Atrapa clientes" },
{ nombre: "Ajo macho" },
{ nombre: "Aborrecido serás" },
{ nombre: "Arrasa brujería" },
{ nombre: "Amarre matrimonial" },
{ nombre: "Anima sola" },
{ nombre: "Arrasa todo dragón" },
{ nombre: "Arrasa todo coyote" },
{ nombre: "Arcángel Gabriel" },
{ nombre: "Arcángel Rafael" },
{ nombre: "Arcángel Zadkiel" },
{ nombre: "Arcángel Uriel" },
{ nombre: "Arcángel Chamuel" },
{ nombre: "Arcángel Jofiel" },
{ nombre: "Arcángel Miguel" },
{ nombre: "Buena suerte y protección" },
{ nombre: "Brasero" },
{ nombre: "Contra daños" },
{ nombre: "Canela" },
{ nombre: "Chuparosa" },
{ nombre: "Contra embrujo" },
{ nombre: "Cordero manso" },
{ nombre: "Correlona" },
{ nombre: "Corta maldad" },
{ nombre: "Corte y juzgado" },
{ nombre: "Cruz de Caravaca" },
{ nombre: "Cuerno de la abundancia" },
{ nombre: "Cocktel 33" },
{ nombre: "Coyote" },
{ nombre: "Corta espanto" },
{ nombre: "Con nadie mas podrás" },
{ nombre: "Contra envidia" },
{ nombre: "Coco" },
{ nombre: "Chile" },
{ nombre: "Coco/ canela" },
{ nombre: "Corta enfermedad" },
{ nombre: "Desespero" },
{ nombre: "Destierro" },
{ nombre: "Destrancadera" },
{ nombre: "Divina providencia" },
{ nombre: "Doble suerte rápida" },
{ nombre: "Doblegado a mis pies" },
{ nombre: "Domina todo" },
{ nombre: "Don Juan del dinero" },
{ nombre: "Desamarre" },
{ nombre: "Detente enemigo" },
{ nombre: "Divina providencia" },
{ nombre: "Dominio" },
{ nombre: "Odio" },
{ nombre: "Doble suerte rápida" },
{ nombre: "Dólar" },
{ nombre: "Domino mujer" },
{ nombre: "Domino hombre" },
{ nombre: "Estudiante" },
{ nombre: "El bien y el mal" },
{ nombre: "Elegua" },
{ nombre: "Espíritu dominador" },
{ nombre: "Espíritu santo" },
{ nombre: "Espíritu intranquilo" },
{ nombre: "Esposo cumplidor" },
{ nombre: "Éxito" },
{ nombre: "Embrujo de amor" },
{ nombre: "Espanta muerto" },
{ nombre: "Fidelidad" },
{ nombre: "Furia de paciones" },
{ nombre: "Gallina negra" },
{ nombre: "Garrapata" },
{ nombre: "Gato negro" },
{ nombre: "Gana juicio" },
{ nombre: "Harás mi voluntad" },
{ nombre: "Hechizo de amor" },
{ nombre: "Hechizo gitano" },
{ nombre: "Herradura" },
{ nombre: "Jala jala" },
{ nombre: "Justo juez" },
{ nombre: "Jesús malverde" },
{ nombre: "Jorobado" },
{ nombre: "Juan conquistador" },
{ nombre: "Juzgador de leyes" },
{ nombre: "Job (Trabajo)" },
{ nombre: "Lavanda" },
{ nombre: "Levanta negocios" },
{ nombre: "Limpia aura" },
{ nombre: "Limpia cuerpo" },
{ nombre: "Limpias y despojos" },
{ nombre: "Limpias" },
{ nombre: "Llama cliente" },
{ nombre: "Llama dinero" },
{ nombre: "Luvia de dinero" },
{ nombre: "Lluvia de estrellas" },
{ nombre: "Lluvia de suerte" },
{ nombre: "Mano poderosa" },
{ nombre: "Miel de amor" },
{ nombre: "Nardos" },
{ nombre: "Nueve yerbas del indio" },
{ nombre: "Niño de la salud" },
{ nombre: "Obatala" },
{ nombre: "Ogum" },
{ nombre: "Patchuly" },
{ nombre: "Págame pronto" },
{ nombre: "Para todo" },
{ nombre: "Paz en el hogar" },
{ nombre: "Perro cazador" },
{ nombre: "Piensa en mi" },
{ nombre: "Pierde rumbo" },
{ nombre: "Prosperidad" },
{ nombre: "Protección" },
{ nombre: "Quédate en casa" },
{ nombre: "Quiéreme siempre" },
{ nombre: "Quiero trabajo pronto" },
{ nombre: "Quita maldición" },
{ nombre: "Quita vicio" },
{ nombre: "Retira trabajo negro" },
{ nombre: "Regresa a casa" },
{ nombre: "Regresa a mi" },
{ nombre: "Regresa pronto" },
{ nombre: "Retiro" },
{ nombre: "Retiro" },
{ nombre: "Retiro" },
{ nombre: "Reversible" },
{ nombre: "Rey salomón" },
{ nombre: "Rompe camino" },
{ nombre: "Rompe maleficios" },
{ nombre: "Rompe hechizos" },
{ nombre: "Rosas" },
{ nombre: "Rosas con miel" },
{ nombre: "Saca sal" },
{ nombre: "Separa amantes" },
{ nombre: "Shangoo" },
{ nombre: "Siete arcángeles" },
{ nombre: "Siete potencias" },
{ nombre: "Siete machos" },
{ nombre: "Siete nudos" },
{ nombre: "Siete veces reversible" },
{ nombre: "Sígueme y obedéceme" },
{ nombre: "Solo mío serás" },
{ nombre: "Santa muerte blanca" },
{ nombre: "Santa muerte roja" },
{ nombre: "Santa muerte negra" },
{ nombre: "Santa muerte (del titulo que usted necesite)" },
{ nombre: "Taba pocas" },
{ nombre: "Triple suerte" },
{ nombre: "Tumba trabajo" },
{ nombre: "Tumba trabajo negro" },
{ nombre: "Te odiara tu amante" },
{ nombre: "Tapa camino" },
{ nombre: "Unión" },
{ nombre: "Unión familiar" },
{ nombre: "Unión matrimonial" },
{ nombre: "Ven a mi" },
{ nombre: "Velo de novia" },
{ nombre: "Ven dinero" },
{ nombre: "Vence batallas" },
{ nombre: "Vuelve conmigo" },
{ nombre: "Vete lejos" },
{ nombre: "Voladora" },
{ nombre: "Vencedor" },
{ nombre: "Ventas rápidas" },
{ nombre: "Yemaya" },
{ nombre: "Yo domino a mi hija" },
{ nombre: "Yo domino hijo" },
{ nombre: "Yo domino a mi hombre" },
{ nombre: "Yo domino a mi mujer" },
{ nombre: "Yo domino a mi patrón" },
{ nombre: "Yo puedo mas que tu" },
{ nombre: "Zodiaco" },
{ nombre: "Orula" },
{ nombre: "Oshun" },

      // EDITAR: agrega más variantes aquí
    ]
  },

  // ─────────────────────────────────────────────────────
  //  PRODUCTO 4
  // ─────────────────────────────────────────────────────
  {
    titulo:      "Colonias Naturales",
    img:         "IMG_4722.jpeg",
    descripcion: "Colonias naturales a base de extractos de plantas para garantizar la alineación del individuo.",
    precioBase:  "Desde $28 mxn / unidad",
    variantes: [
      { nombre: "Abre Camino" },
  { nombre: "Agua Florida" },
  { nombre: "Amansa Guapo" },
  { nombre: "Amarre" },
  { nombre: "Amor Verdadero" },
  { nombre: "Atrae Clientes" },
  { nombre: "Atrae Dinero" },
  { nombre: "Atracción" },
  { nombre: "Buena Suerte" },
  { nombre: "Camino Abierto" },
  { nombre: "Canela" },
  { nombre: "Changó" },
  { nombre: "Contra Envidia" },
  { nombre: "Despojo" },
  { nombre: "Destrancadera" },
  { nombre: "Dinero Rápido" },
  { nombre: "Dominio" },
  { nombre: "Elegguá" },
  { nombre: "Endulzamiento" },
  { nombre: "Espanta Espíritus" },
  { nombre: "Espíritu Dominador" },
  { nombre: "Éxito" },
  { nombre: "Jazmín" },
  { nombre: "Juan del Dominio" },
  { nombre: "Lavanda" },
  { nombre: "Limpia Aura" },
  { nombre: "Limpia General" },
  { nombre: "Naranja" },
  { nombre: "Obatalá" },
  { nombre: "Open Road" },
  { nombre: "Oshún" },
  { nombre: "Palo Santo" },
  { nombre: "Pasión" },
  { nombre: "Prosperidad" },
  { nombre: "Protección Total" },
  { nombre: "Pusanga" },
  { nombre: "Quita Mal de Ojo" },
  { nombre: "Rompe Brujería" },
  { nombre: "Rosa" },
  { nombre: "Ruda" },
  { nombre: "Saca Sal" },
  { nombre: "Sándalo" },
  { nombre: "Sensación Nocturna" },
  { nombre: "Siete Potencias" },
  { nombre: "Triple Suerte" },
  { nombre: "Ven a Mí" },
  { nombre: "Ven Dinero" },
  { nombre: "Violeta" },
  { nombre: "Yemayá" },
  { nombre: "7 Potencias Africanas" }
      // EDITAR: agrega más variantes aquí
    ]
  },

  // ─────────────────────────────────────────────────────
  //  PRODUCTO 5
  // ─────────────────────────────────────────────────────
  {
    titulo:      "Veladoras Jumbo",
    img:         "jumbo.jpeg",
    descripcion: "Veladoras Jumbo designadas para maximizar la petición del individuo.",
    precioBase:  "Desde $680 mxn / caja (6 pzas)",
    variantes: [
      { nombre: "Jumbo Roja — Amor" },
      { nombre: "Jumbo Verde — Dinero" },
      { nombre: "Jumbo Blanca — Purificación" },
      { nombre: "Jumbo Negra — Protección" },
      { nombre: "Jumbo Morada — Espiritualidad" },
      // EDITAR: agrega más variantes aquí
    ]
  },

  // ─────────────────────────────────────────────────────
  //  PRODUCTO 6
  // ─────────────────────────────────────────────────────
  {
    titulo:      "Sobres de Hierbas",
    img:         "sobres.jpeg",
    descripcion: "Mezcla de hierbas aromáticas preparadas para baños, limpias y rituales.",
    precioBase:  "Desde $19 mxn / unidad",
    variantes: [
       { nombre: "Abre Camino" },
  { nombre: "Agua Florida" },
  { nombre: "Amansa Guapo" },
  { nombre: "Amarre" },
  { nombre: "Amor Verdadero" },
  { nombre: "Atrae Clientes" },
  { nombre: "Atrae Dinero" },
  { nombre: "Atracción" },
  { nombre: "Buena Suerte" },
  { nombre: "Camino Abierto" },
  { nombre: "Canela" },
  { nombre: "Changó" },
  { nombre: "Contra Envidia" },
  { nombre: "Despojo" },
  { nombre: "Destrancadera" },
  { nombre: "Dinero Rápido" },
  { nombre: "Dominio" },
  { nombre: "Elegguá" },
  { nombre: "Endulzamiento" },
  { nombre: "Espanta Espíritus" },
  { nombre: "Espíritu Dominador" },
  { nombre: "Éxito" },
  { nombre: "Jazmín" },
  { nombre: "Juan del Dominio" },
  { nombre: "Lavanda" },
  { nombre: "Limpia Aura" },
  { nombre: "Limpia General" },
  { nombre: "Naranja" },
  { nombre: "Obatalá" },
  { nombre: "Open Road" },
  { nombre: "Oshún" },
  { nombre: "Palo Santo" },
  { nombre: "Pasión" },
  { nombre: "Prosperidad" },
  { nombre: "Protección Total" },
  { nombre: "Pusanga" },
  { nombre: "Quita Mal de Ojo" },
  { nombre: "Rompe Brujería" },
  { nombre: "Rosa" },
  { nombre: "Ruda" },
  { nombre: "Saca Sal" },
  { nombre: "Sándalo" },
  { nombre: "Sensación Nocturna" },
  { nombre: "Siete Potencias" },
  { nombre: "Triple Suerte" },
  { nombre: "Ven a Mí" },
  { nombre: "Ven Dinero" },
  { nombre: "Violeta" },
  { nombre: "Yemayá" },
  { nombre: "7 Potencias Africanas" }
      // EDITAR: agrega más variantes aquí
    ]
  },

  // ─────────────────────────────────────────────────────
  //  PRODUCTO 7
  // ─────────────────────────────────────────────────────
  {
    titulo:      "Jabones Standard",
    img:         "jabones.jpeg",
    descripcion: "Barras de jabón esotéricos naturales versión standard.",
    precioBase:  "Desde $10 mxn / unidad",
    variantes: [
       { nombre: "Abre Camino" },
  { nombre: "Agua Florida" },
  { nombre: "Amansa Guapo" },
  { nombre: "Amarre" },
  { nombre: "Amor Verdadero" },
  { nombre: "Atrae Clientes" },
  { nombre: "Atrae Dinero" },
  { nombre: "Atracción" },
  { nombre: "Buena Suerte" },
  { nombre: "Camino Abierto" },
  { nombre: "Canela" },
  { nombre: "Changó" },
  { nombre: "Contra Envidia" },
  { nombre: "Despojo" },
  { nombre: "Destrancadera" },
  { nombre: "Dinero Rápido" },
  { nombre: "Dominio" },
  { nombre: "Elegguá" },
  { nombre: "Endulzamiento" },
  { nombre: "Espanta Espíritus" },
  { nombre: "Espíritu Dominador" },
  { nombre: "Éxito" },
  { nombre: "Jazmín" },
  { nombre: "Juan del Dominio" },
  { nombre: "Lavanda" },
  { nombre: "Limpia Aura" },
  { nombre: "Limpia General" },
  { nombre: "Naranja" },
  { nombre: "Obatalá" },
  { nombre: "Open Road" },
  { nombre: "Oshún" },
  { nombre: "Palo Santo" },
  { nombre: "Pasión" },
  { nombre: "Prosperidad" },
  { nombre: "Protección Total" },
  { nombre: "Pusanga" },
  { nombre: "Quita Mal de Ojo" },
  { nombre: "Rompe Brujería" },
  { nombre: "Rosa" },
  { nombre: "Ruda" },
  { nombre: "Saca Sal" },
  { nombre: "Sándalo" },
  { nombre: "Sensación Nocturna" },
  { nombre: "Siete Potencias" },
  { nombre: "Triple Suerte" },
  { nombre: "Ven a Mí" },
  { nombre: "Ven Dinero" },
  { nombre: "Violeta" },
  { nombre: "Yemayá" },
  { nombre: "7 Potencias Africanas" }
      // EDITAR: agrega más variantes aquí
    ]
  },

  // ─────────────────────────────────────────────────────
  //  AGREGAR MÁS PRODUCTOS:
  //  Copia el bloque de abajo y llénalo con tus datos
  // ─────────────────────────────────────────────────────
  // {
  //   titulo:      "Nombre del producto",
  //   img:         "foto.jpg",
  //   descripcion: "Descripción del producto.",
  //   precioBase:  "Desde $XX mxn",
  //   variantes: [
  //     { nombre: "Variante 1" },
  //     { nombre: "Variante 2" },
  //   ]
  // },

];
